# Generated by Django 5.0 on 2024-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profilepicture_topiccompletion_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://example.com/path/to/default-image.jpg', null=True),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
