# Generated by Django 5.0 on 2024-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='practice_url',
            field=models.URLField(blank=True, null=True, verbose_name='Practice (Leetcode URL)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_discription',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
