# Generated by Django 5.1.3 on 2024-11-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2023/02/18/11/00/icon-7797704_1280.png', null=True),
        ),
    ]
